---

- name: Ensure redis is installed
  apt:
    name: "{{ redis_package }}"
    state: present
    policy_rc_d: 101

- name: Install redis_extra_packages
  apt:
    name: "{{ redis_extra_packages }}"
    state: present
