---

- name: Install redis
  openbsd_pkg:
    name: "{{ redis_package }}"
    state: present

- name: Install redis_extra_packages
  openbsd_pkg:
    name: "{{ redis_extra_packages }}"
    state: present
